name: Laboratorio Final DevSecOps

on:
  push:
    branches: [ "feature_laboratorio_final" ]
  pull_request:
    branches: [ "feature_laboratorio_final" ]

jobs:
  SAST:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up JDK 11
       uses: actions/setup-java@v4
       with:
        java-version: '11'
        distribution: 'temurin'

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

     - name: Initialize CodeQL
       uses: github/codeql-action/init@v3
       with:
          languages: java-kotlin
          build-mode: none
          queries: |
            security-and-quality

     - name: Build with Gradle Wrapper
       run: ./gradlew build
          
 #    - name: Perform CodeQL Analysis
 #      uses: github/codeql-action/analyze@v3
 #      with:
 #         category: "/language:java-kotlin"  
              

   #  - name: Wait for CodeQL processing
   #    run: sleep 40

   #  - name: Fail pipeline if vulnerabilities exist
   #    run: |
      
   #       echo "Checking CodeQL alerts..."
      
   #       RESPONSE=$(curl -s \
   #         -H "Accept: application/vnd.github+json" \
   #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
   #         "https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts?state=open&ref=refs/heads/feature_laboratorio_final")
      
   #       echo "$RESPONSE" | jq -r '.[] | "\(.rule.security_severity_level) - \(.rule.description)"'
      
   #       SEVERITY_FOUND=$(echo "$RESPONSE" | jq -r '.[] | .rule.security_severity_level' | grep -E 'medium|high|critical' || true)
      
   #       if [ ! -z "$SEVERITY_FOUND" ]; then
   #         echo "Medium/High/Critical vulnerabilities detected"
   #         exit 1
   #       else
   #         echo "No vulnerabilities found"
   #       fi

  SCA: 
   # needs: SAST
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'  

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew   

 #     - name: Build with Gradle Wrapper
 #       run: ./gradlew build

 #     - name: Dependency Check
 #       uses: dependency-check/Dependency-Check_Action@main
 #       env:
 #        JAVA_HOME: /opt/jdk
 #       with:
 #         project: 'laboratorio final'
 #         path: '.'
 #         format: 'HTML'
 #         args: >
 #           --disableCentral
          
 #     - name: Upload Test results
 #       uses: actions/upload-artifact@master
 #       with:
 #          name: Depcheck report
 #          path: ${{github.workspace}}/reports

      # Validar vulnerabilidades
 #     - name: Fail pipeline if vulnerabilities exist
 #       run: |
        
 #           echo "===== Vulnerabilities Found ====="
        
 #           grep -E "CRITICAL|HIGH|MEDIUM" reports/dependency-check-report.html | head -20
        
 #           if grep -E "CRITICAL|HIGH|MEDIUM" reports/dependency-check-report.html
 #           then
 #             echo ""
 #             echo "=========================================="
 #             echo " Medium/High/Critical vulnerabilities detected"
 #             echo " Pipeline stopped due security policy"
 #             echo "=========================================="
 #       
 #             exit 1
 #           else
 #             echo "No vulnerabilities found"
 #           fi     

  Imagen-Docker :
     # needs: [SAST, SCA]
     runs-on: ubuntu-latest
     steps: 

      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set Up JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'  

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew   

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Validate generated files
        run: |
          ls -la build/libs
      
      - name: Rename JAR
        run: |
          cp build/libs/spring-petclinic-2.6.0.jar spring-petclinic-2.6.0.jar
     
      - name: Docker Login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{secrets.USER_DOCKER}}
          password: ${{secrets.PASS_DOCKER}}    
      - name : Docker build
        run: | 
         docker build --tag  vitoko25/laboratorio-final:latest .

                  
      - name : docker push
        run : |
          docker  push vitoko25/laboratorio-final:latest

